# Generated by Django 5.0.1 on 2024-04-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_address_teacher_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Techs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='featured_image',
            field=models.ImageField(null=True, upload_to='course_imgs/'),
        ),
    ]
