# Generated by Django 5.0.1 on 2024-04-22 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_course_techs_course_featured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Techs',
            new_name='techs',
        ),
    ]
