# Generated by Django 5.0.1 on 2024-04-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_courserating'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='course_imgs/'),
        ),
    ]
