# Generated by Django 5.0.1 on 2024-04-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_teacher_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='teacher_profile_imgs/'),
        ),
    ]
